In [40]:
import pandas as pd
import numpy as np

df = pd.read_csv("/kaggle/input/titanic/train.csv")
print(df.head())


   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [68]:
df.drop("Name", axis=1, inplace=True)
df.drop("Ticket", axis=1, inplace=True)
df.drop("PassengerId", axis=1, inplace=True)
df.drop("Cabin", axis=1, inplace=True)
df.drop("Embarked", axis=1, inplace=True)


KeyError: "['Name'] not found in axis"

In [67]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
dtypes: float64(2), int64(4), object(1)
memory usage: 48.9+ KB


In [69]:
print(df.isnull().sum())

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
dtype: int64


In [70]:
updated_df = df
updated_df['Age'] = updated_df['Age'].fillna(updated_df['Age'].mean())
updated_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
dtypes: float64(2), int64(4), object(1)
memory usage: 48.9+ KB


In [71]:
updated_df = df.dropna(axis=1)
updated_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
dtypes: float64(2), int64(4), object(1)
memory usage: 48.9+ KB


In [73]:
newdf=df
updated_df = newdf.dropna(axis=0)

# Extract target variable (Survived)
y1 = updated_df['Survived']

# Drop the Survived column from the features
updated_df.drop("Survived", axis=1, inplace=True)

# Display the updated DataFrame information
updated_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Pclass  891 non-null    int64  
 1   Sex     891 non-null    object 
 2   Age     891 non-null    float64
 3   SibSp   891 non-null    int64  
 4   Parch   891 non-null    int64  
 5   Fare    891 non-null    float64
dtypes: float64(2), int64(3), object(1)
memory usage: 41.9+ KB


In [74]:
# Importing pandas and numpy libraries
import pandas as pd
import numpy as np

# Creating a dummy DataFrame of 14 numbers randomly ranging from 1−100 for age
df = pd.DataFrame({'Age': [42, 15, 67, 55, 1, 29, 75, 89, 4, 10, 15, 38, 22, 77]})

# Printing DataFrame before sorting Continuous to Categories
print("DataFrame before categorization:\n", df)

# Categorizing Age into 4 Categories
# Baby/Toddler: (0,3], 0 is excluded & 3 is included
# Child: (3,17], 3 is excluded & 17 is included
# Adult: (17,63], 17 is excluded & 63 is included
# Elderly: (63,99], 63 is excluded & 99 is included
df['Label'] = pd.cut(x=df['Age'], bins=[0, 3, 17, 63, 99],
                     labels=['Baby/Toddler', 'Child', 'Adult', 'Elderly'])

# Printing DataFrame after sorting Continuous to Categories
print("\nDataFrame after categorization:\n", df)

# Check the number of values in each bin
print("\nCategories: ")
print(df['Label'].value_counts())


DataFrame before categorization:
     Age
0    42
1    15
2    67
3    55
4     1
5    29
6    75
7    89
8     4
9    10
10   15
11   38
12   22
13   77

DataFrame after categorization:
     Age         Label
0    42         Adult
1    15         Child
2    67       Elderly
3    55         Adult
4     1  Baby/Toddler
5    29         Adult
6    75       Elderly
7    89       Elderly
8     4         Child
9    10         Child
10   15         Child
11   38         Adult
12   22         Adult
13   77       Elderly

Categories: 
Label
Adult           5
Child           4
Elderly         4
Baby/Toddler    1
Name: count, dtype: int64


In [76]:


# Import dataset
df = pd.read_csv('../../data/Iris.csv')

# Display unique species before encoding
print(df['species'].unique())

# Import label encoder
from sklearn import preprocessing

# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()

# Encode labels in column 'species'.
df['species'] = label_encoder.fit_transform(df['species'])

# Display unique species after encoding
print(df['species'].unique())


FileNotFoundError: [Errno 2] No such file or directory: '../../data/Iris.csv'

In [77]:
# Example of an ordinal encoding
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder

# Define data
data = asarray([['red'], ['green'], ['blue']])
print("Original data:\n", data)

# Define ordinal encoding
encoder = OrdinalEncoder()

# Transform data
result = encoder.fit_transform(data)
print("\nEncoded data:\n", result)


Original data:
 [['red']
 ['green']
 ['blue']]

Encoded data:
 [[2.]
 [1.]
 [0.]]


In [78]:
# Example of one-hot encoding
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder

# Define data
data = asarray([['red'], ['green'], ['blue']])
print("Original data:\n", data)

# Define one-hot encoding
encoder = OneHotEncoder(sparse_output=False)

# Transform data
onehot = encoder.fit_transform(data)
print("\nOne-hot encoded data:\n", onehot)


Original data:
 [['red']
 ['green']
 ['blue']]

One-hot encoded data:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [79]:
import pandas as pd

# Create data
df = pd.DataFrame([
    [180000, 110, 18.9, 1400],
    [360000, 905, 23.4, 1800],
    [230000, 230, 14.0, 1300],
    [60000, 450, 13.5, 1500]],
    columns=['Col A', 'Col B', 'Col C', 'Col D'])

# Make a copy of the DataFrame
df_min_max_scaled = df.copy()

# Apply min-max normalization
for column in df_min_max_scaled.columns:
    df_min_max_scaled[column] = (df_min_max_scaled[column] - df_min_max_scaled[column].min()) / (df_min_max_scaled[column].max() - df_min_max_scaled[column].min())

# View normalized data
print(df_min_max_scaled)


      Col A     Col B     Col C  Col D
0  0.400000  0.000000  0.545455    0.2
1  1.000000  1.000000  1.000000    1.0
2  0.566667  0.150943  0.050505    0.0
3  0.000000  0.427673  0.000000    0.4
